server:
  port: 8080

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:mem:mydb
    username: test
    password: test
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
macbook:
  orders:
    pageSize: 5




---