spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:h2:mem:dev
    username: dev
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect


---
spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:h2:mem:prod
    username: prod
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
